language: node_js
node_js:
  - '8'
cache: yarn
branches:
  only:
  - develop
before_script:
  - git remote set-url origin "https://github.com/radiokashana/radiokashana.github.io.git"
  - git config --global user.email "yorch.veintemil@gmail.com"
  - git config --global user.name "Travis-CI"
script:
  - yarn deploy
